### ISSUE TITLE
do you need help?

### ISSUE THREAD

**Issue by Sirherobrine23** [Kastilo/OpenAC#1]
I haven't updated my README, but here's a simple example.

```yml
name: OpenWRT Github CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - uses: Sirherobrine23/Actions-Build-Openwrt@main
      with:
        config: ".config"

    - name: Upload To Releases
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Build to ${{ env.DEVICE_NAME }}, Run ID ${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body_path: ${{ env.BODY_PATH }}
        files: ${{ env.FIRMWARE_PATH }}/*
```

**Comment by Kastilo** [comment]
I see, thanks. I'm just trying to figure out how workflows work because I have 4 OpenWRT devices, I'm trying to get these to autobuild buuuuut I've never actually played with workflows before

**Comment by Kastilo** [comment]
> I haven't updated my README, but here's a simple example.
> 
> ```yaml
> name: OpenWRT Github CI
> on: [push]
> 
> jobs:
>   build:
>     runs-on: ubuntu-latest
>     name: Build
>     steps:
>     - name: Checkout
>       uses: actions/checkout@main
> 
>     - uses: Sirherobrine23/Actions-Build-Openwrt@main
>       with:
>         config: ".config"
> 
>     - name: Upload To Releases
>       uses: softprops/action-gh-release@v1
>       env:
>         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>       with:
>         name: Build to ${{ env.DEVICE_NAME }}, Run ID ${{ github.run_id }}
>         tag_name: ${{ github.run_id }}
>         body_path: ${{ env.BODY_PATH }}
>         files: ${{ env.FIRMWARE_PATH }}/*
> ```

How would I add custom packages, just as the default theme I use for my images Argon?

[Source](https://forum.openwrt.org/t/theme-argon-main-thread/122457/2)

git clone -b master https://github.com/jerrykuku/luci-theme-argon package/luci-theme-argon
git clone -b master https://github.com/jerrykuku/luci-app-argon-config package/luci-app-argon-config

**Comment by Sirherobrine23** [comment]
one of the workflows from my repositories: https://github.com/Sirherobrine23/MultiOpenwrtBuild/blob/main/.github/workflows/build.yaml

It's easy, my flow you can create several folders inside the repository with the device name, example folder:
```
root
|------- x64
          |----- files/ (You can add any file in the image root from here)
          |------ .config
          |------ p1.sh (Post clone repo: here you can build a simple Shell Script to edit any file directly in the OpenWRT folder)
          |------ p2.sh (Post build image: after installing the OpenWRT packages and doing the make build, if I did it successfully it will be called)
....

**Comment by Sirherobrine23** [comment]
more input in `with`

```yml
    - uses: Sirherobrine23/Actions-Build-Openwrt@main
      with: # <-- here to add your custom repo and more options
        config: ".config"
```

| input | description | default |
| ----- | ----------- | ------- |
| url      | Git Repository URL | https://git.openwrt.org/openwrt/openwrt.git |
| branch | Git Repository Branch | master |
| showlog | Show build logs | true |
| workdir | ./ | Working directory |
| config | Openwrt Build File path (make menuconfig file in the host computer) | - |
| p1 | File Bash Script for execute before feed Update | p1.sh |
| p2 | File Bash Script for execute before feed Update | p2.sh |
